version: "3.9"

networks:
  dogefuzz_benchmark:
    name: dogefuzz_benchmark

services:
  geth:
    container_name: dogefuzz_geth
    build: https://github.com/faustocarva/enhanced-go-ethereum.git#main
    environment:
      CHAIN_ID: 1900
      NODE_WALLET_ADDRESS: '0x095e7e130af11aebd04fb5fb81193bda66eefb81'
      NODE_WALLET_PRIVATE_KEY: 'f33ff13222d9141bcfe072f4c148026bf0187a3ca1f7c4063a7f3e4aff6591a5'
      NODE_WALLET_BALANCE: '20000000000000000000' # 20 ETH
      DEPLOYER_WALLET_ADDRESS: '0x149efdd75031aa34c01a01da9fb8e859c5166b49'
      DEPLOYER_WALLET_PRIVATE_KEY: '1c8d8e900c1b8c6554d995e172c3f58ebaf0e035be4f597e89aa3599cd970d9b'
      DEPLOYER_WALLET_BALANCE: '1000000000000000000000000' # 1000 ETH
      AGENT_WALLET_ADDRESS: '0xae02fb2776c3e3051e25af26712b6b34b70e5266'
      AGENT_WALLET_PRIVATE_KEY: '39a7089e3f7e093b900bc8e98e6e5cba4639cd04d3e944ce1ddd2ca1595b7b87'
      AGENT_WALLET_BALANCE: '1000000000000000000000000' # 1000 ETH
      NODE_PASSWORD: '123456'
      GAS_LIMIT: '8000000'
      FUZZER_HOST: 'dogefuzz'
      FUZZER_PORT: '3456'
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "-h", "Content-Type: application/json", "--data", '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", false],"id":1}', "http://localhost:8545"]
      interval: 3s
      timeout: 10s
      retries: 10
    networks:
      - dogefuzz_benchmark
  vandal:
    container_name: dogefuzz_vandal
    build: https://github.com/dogefuzz/vandal-api.git#main
    restart: on-failure
    networks:
      - dogefuzz_benchmark
  dogefuzz:
    container_name: dogefuzz_api
    build: https://github.com/dogefuzz/dogefuzz.git#main
    ports:
      - "3456:3456"
    networks:
      - dogefuzz_benchmark
    restart: on-failure
    environment:
      DOGEFUZZ_REPORTER_TYPE: "webhook"
      DOGEFUZZ_REPORTER_WEBHOOKENDPOINT: "http://benchmark:5000"
      DOGEFUZZ_VANDAL_ENDPOINT: "http://vandal:5000"
      DOGEFUZZ_GETH_NODEADDRESS: "http://geth:8545"
      DOGEFUZZ_FUZZER_BATCHSIZE: 1
      DOGEFUZZ_FUZZER_PENDINGTRANSACTIONSTHRESHOLD: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3456/ping"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      geth:
        condition: service_healthy

